/**
 * Build a portable .exe pinned to one machine.
 *
 * Usage:
 *   npm run dist -- "SWF 8X11HSP" DRAWING
 *   npm run dist -- "SWF BUN 630 (36)" STRANDING
 *
 * Output:
 *   dist\<Machine Name>.exe
 */
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const args = process.argv.slice(2);
const processIdx = args.findIndex((a) => /^(DRAWING|STRANDING)$/i.test(a));
let machine = '';
let processCd = 'DRAWING';

if (processIdx >= 0) {
  machine = args.slice(0, processIdx).join(' ').trim();
  processCd = String(args[processIdx]).toUpperCase();
} else {
  machine = args.join(' ').trim();
}

const baseUrl =
  process.env.WIDGET_BASE || 'http://194.1.31.11:8082/machine-efficiency-widget';

if (!machine) {
  console.error('Usage: npm run dist -- "<Machine Name>" [DRAWING|STRANDING]');
  console.error('Example: npm run dist -- "SWF 8X11HSP" DRAWING');
  process.exit(1);
}

if (processCd !== 'DRAWING' && processCd !== 'STRANDING') {
  console.error('Process must be DRAWING or STRANDING');
  process.exit(1);
}

const root = __dirname;
const configPath = path.join(root, 'machine-config.js');
const pkgPath = path.join(root, 'package.json');

const configJs = `/**
 * Pinned machine for this widget build.
 * Generated by build-widget.js — do not edit by hand for release builds.
 */
module.exports = {
  machine: ${JSON.stringify(machine)},
  process: ${JSON.stringify(processCd)},
  baseUrl: ${JSON.stringify(baseUrl)}
};
`;

fs.writeFileSync(configPath, configJs, 'utf8');
console.log('Wrote machine-config.js →', machine, processCd);

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
pkg.build = pkg.build || {};
pkg.build.productName = machine;
pkg.build.appId = `swf.machine.efficiency.${machine.replace(/[^a-zA-Z0-9]+/g, '.').toLowerCase()}`;
pkg.build.artifactName = '${productName}.${ext}';
pkg.build.files = ['main.js', 'package.json', 'machine-config.js'];
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
console.log('package.json productName →', machine);

const result = spawnSync(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  ['electron-builder', '--win', 'portable'],
  { cwd: root, stdio: 'inherit', shell: true }
);

if (result.status !== 0) {
  process.exit(result.status || 1);
}

const exeName = `${machine}.exe`;
const exePath = path.join(root, 'dist', exeName);
if (fs.existsSync(exePath)) {
  console.log('\nBuilt:', exePath);
} else {
  console.log('\nBuild finished. Check dist\\ for', exeName);
}
