/**
 * Pinned machine for this widget build.
 * Generated by build-widget.js — do not edit by hand for release builds.
 */
module.exports = {
  machine: "SWF 8X11HSP",
  process: "DRAWING",
  baseUrl: "http://194.1.31.11:8082/machine-efficiency-widget"
};
